# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
        gemfile:
          - gemfiles/rails_7_0.gemfile
          - gemfiles/rails_7_1.gemfile
          - gemfiles/rails_7_2.gemfile
          - gemfiles/rails_8_0.gemfile
          - gemfiles/activerecord_7_0.gemfile
          - gemfiles/activerecord_7_1.gemfile
          - gemfiles/activerecord_7_2.gemfile
          - gemfiles/activerecord_8_0.gemfile
        exclude:
          - ruby-version: '3.1'
            gemfile: gemfiles/rails_8_0.gemfile
          - ruby-version: '3.1'
            gemfile: gemfiles/activerecord_8_0.gemfile

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install gems
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      run: bundle install

    - name: Run tests
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      run: bundle exec rake
